inherit_from: .rubocop_todo.yml

AllCops:
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
