inherit_from: .rubocop_todo.yml

AllCops:
  DisplayStyleGuide: true
  ExtraDetails: true

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
