version: 2.1

executors:
  ruby:
    parameters:
      version:
        description: "ruby version"
        type: string
    docker:
      - image: cimg/ruby:<<parameters.version>>

jobs:
  ruby:
    parameters:
      version:
        description: "ruby version"
        type: string
    executor:
      name: ruby
      version: <<parameters.version>>
    steps:
      - checkout
      - run:
          name: Install gems
          command: bundle
      - run:
          name: Run RuboCop
          command: bundle exec rubocop --fail-fast
      - run:
          name: Run Rake
          command: bundle exec rake

      # Save artifacts
      - store_artifacts:
          path: coverage/

      # Save test results
      - store_test_results:
          path: test-results

workflows:
  test-matrix:
    jobs:
      - ruby:
          matrix:
            parameters:
              version:
                - "3.0"
                - "3.1"
                - "3.2"
                - "3.3"
                - "3.4"
  weekly:
    jobs:
      - ruby:
          matrix:
            parameters:
              version:
                - "3.0"
                - "3.1"
                - "3.2"
                - "3.3"
                - "3.4"
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
